### ISSUE TITLE
Youtube api changed, extension stopped working

### ISSUE THREAD

**Issue by skoften** [click-rain/videolink#17]
http://gdata.youtube.com/feeds/api/videos/AZb54NlQZms?v=2&alt=jsonc

{"apiVersion":"2.1","error":{"code":410,"message":"No longer available","errors":[{"domain":"GData","code":"NoLongerAvailableException","internalReason":"No longer available"}]}}

**Comment by bryanburgers** [comment]
This is fixed in v1.5.0. See [this commit](https://github.com/click-rain/videolink/commit/c1340b74b6fb3d74487e6a6d89c70bc66bb001ca) for info.

**Comment by skoften** [comment]
great, thanks!

**Comment by Yatish0833** [comment]
Still facing this issue.
https://gdata.youtube.com/feeds/api/videos/xAHjjKf7A1Y?v=2&alt=jsonc

{"apiVersion":"2.1","error":{"code":410,"message":"No longer available","errors":[{"domain":"GData","code":"NoLongerAvailableException","internalReason":"No longer available"}]}}

**Comment by bryanburgers** [comment]
@Yatish0833 see my comment in #19.
